# -*- coding: utf-8 -*-
"""data_loader.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ap4t0rrfNlciJosD-7OhzQMJcVSIqxZX
"""

import json
from pathlib import Path
from config import Config


def _to_display_role_name(internal_name):
    """Короткое название профессии для UI (без «Скиллсет», нормализованная форма)."""
    if not internal_name:
        return internal_name
    s = internal_name.strip()
    if s.startswith("Скиллсет "):
        s = s[len("Скиллсет "):].strip()
    overrides = {
        "Менеджер проекта в IT": "Менеджер проектов в IT",
        "Ручные тестировщики": "Ручной тестировщик",
        "Автотестировщики": "Автотестировщик",
        "Фронтенд разработчиков": "Фронтенд-разработчик",
        "ML-разработчиков": "ML-разработчик",
        "Android-разработчиков": "Android-разработчик",
        "iOS-разработчиков": "iOS-разработчик",
        "Тех. менеджер": "Технический менеджер",
    }
    return overrides.get(s, s)


class DataLoader:
    def __init__(self):
        self.skills = self._load_json(Config.SKILLS_FILE)
        self.atlas_params = self._load_json(Config.ATLAS_FILE)

        self.skills_map = {s.get('Навык') or s.get('name'): s for s in self.skills}
        self.atlas_map = {a.get('Параметр') or a.get('Parameter'): a for a in self.atlas_params}

        internal_roles = set()
        for skill in self.skills:
            prof = skill.get('Профессия (лист)') or skill.get('Профессия') or skill.get('Привязка к профессии')
            if isinstance(prof, str):
                internal_roles.add(prof)
        self._internal_to_display = {internal: _to_display_role_name(internal) for internal in internal_roles}
        self._display_to_internal = {disp: internal for internal, disp in self._internal_to_display.items()}

    @staticmethod
    def _load_json(path):
        path = Path(path)
        if not path.is_absolute():
            path = Path(__file__).resolve().parent / path
        with open(path, 'r', encoding='utf-8') as f:
            return json.load(f)

    def get_role_requirements(self, role_name, grade):
        """
        Динамически собирает требования из clean_skills.json и atlas_params.
        НЕ требует отдельного файла role_definitions.json!
        """
        if not role_name or not str(role_name).strip():
            return {}
        requirements = {}

        # Маппинг грейда в числовой уровень (1=Basic, 2=Proficiency, 3=Advanced)
        grade_to_level = {
            "Junior": 1,
            "Middle": 2,
            "Senior": 3,
            "Lead": 3,
            "Expert": 3,
        }
        target_level = grade_to_level.get(grade, 2)

        # 1. Фильтруем навыки по профессии (поля из clean_skills.json)
        for skill in self.skills:
            skill_name = skill.get('Навык') or skill.get('name')
            professions = (
                skill.get('Профессия (лист)') or
                skill.get('Профессия') or
                skill.get('Привязка к профессии') or
                skill.get('Profession') or
                []
            )
            if isinstance(professions, str):
                professions = [professions]

            if role_name in professions:
                requirements[skill_name] = target_level

        # 2. Добавляем ВСЕ параметры Atlas (они нужны всем ролям)
        for param in self.atlas_params:
            param_name = param.get('Параметр') or param.get('Parameter')
            if param_name:
                requirements[param_name] = target_level

        return requirements

    def get_all_roles(self):
        """Список профессий в коротком формате для UI (например, «Менеджер проектов в IT»)."""
        return sorted(self._internal_to_display.values())

    def get_internal_role_name(self, display_name):
        """По отображаемому названию возвращает внутреннее (для get_role_requirements и т.д.)."""
        if not display_name:
            return None
        return self._display_to_internal.get(display_name.strip(), display_name)

    def get_skills_for_role(self, role_name):
        """Список названий навыков для данной профессии (для выпадающего списка по выбранной профессии)."""
        internal = self.get_internal_role_name(role_name) if role_name else None
        if not internal:
            return []
        skill_names = []
        for skill in self.skills:
            skill_name = skill.get('Навык') or skill.get('name')
            professions = (
                skill.get('Профессия (лист)') or
                skill.get('Профессия') or
                skill.get('Привязка к профессии') or
                []
            )
            if isinstance(professions, str):
                professions = [professions]
            if internal in professions:
                skill_names.append(skill_name)
        return sorted(skill_names)